export const categoryGroups = {
  "Open an account": [
    "Why choose Gumroad?",
    "Account settings",
    "Filling out payout settings",
    "Build a website on Gumroad",
    "Having multiple accounts",
    "Protecting creator privacy",
    "Account login security",
    "Things not allowed on Gumroad",
    "Selling services",
    "Adult content on Gumroad",
    "Deleting a Gumroad account",
  ],
  "Add a product": [
    "The products dashboard",
    "Adding a product",
    "Adding cover and thumbnail images",
    "Checkout customization",
    "Custom product URLs",
    "Unpublish or delete a product",
    "Setting up versions on a digital product",
    "Selling memberships",
    "Allowing installment plans",
    '"Pay what you want" pricing',
    "Prepare videos for streaming",
    "Compress videos using Handbrake",
    "Mobile-friendly files",
    "Metadata for audio files",
    "Becoming an affiliate on Gumroad",
    "File size limits",
    "Product bundles",
    "Collaborate with another creator",
    "Gumroad communities",
  ],
  "Start selling": [
    "Testing a purchase",
    "Gumroad Discover",
    "Find a product's URL",
    "The sales dashboard",
    "The sales analytics dashboard",
    "How Gumroad works for customers",
    "The Gumroad Library",
    "Gumroad mobile app",
    "Why customer payments fail",
    "Customers not receiving receipts",
    "Cancel customer memberships",
    "Issuing a refund",
    "Chargebacks on Gumroad",
    "Content protection on Gumroad",
    "Purchasing Power Parity",
    "Creating an Upsell",
    "Tipping",
    "More like this",
    "Set a custom refund policy",
    "Product bundles",
  ],
  "Market your work": [
    "Starting an email newsletter",
    "Send email updates",
    "Send automated emails with Workflows",
    "Customers not receiving emails",
    "Integrating Gumroad into websites",
    "Affiliates on Gumroad",
    "Product bundles",
  ],
  "Get paid": [
    "Getting paid by Gumroad",
    "Connect your Stripe account to Gumroad",
    "Adding PayPal to checkout",
    "Gumroad's fees",
    "The payouts dashboard",
    "Payoneer, Transferwise, and Gumroad",
    "What currency does Gumroad use?",
    "Payout delays",
    "Sales tax on Gumroad",
    "US sales tax on Gumroad",
    "EU & UK VAT on Gumroad",
    "Australian GST on Gumroad",
    "Indirect taxes on sales via Gumroad Discover",
    "Does Gumroad issue form 1099-K and 1099-MISC?",
    "Account suspension FAQ",
    "Fraudulent purchases",
    "Defining fraud on Gumroad",
    "Singaporean GST on Gumroad",
  ],
  Advanced: [
    "Discount codes",
    "Teams and Roles",
    "PDF stamping",
    "Facebook domain verification",
    "Product ratings and reviews",
    "Send customers to the payment form",
    "URL parameters",
    "Setting up a custom domain",
    "Third-party analytics",
    "Turn off third-party trackers",
    "Integrating products with external services",
    "Zapier integrations with Gumroad",
    "Create an application for the API",
    "License keys",
    "Accessibility statement for Gumroad",
    "Customer Moderation",
  ],
  "Contact Gumroad": [
    "Contact Gumroad",
    "Gumroad's refund policy",
    "Report a Gumroad creator",
    "DMCA counter notices",
    "Gumroad's subprocessors",
    "Supported browsers",
    "Jobs at Gumroad",
  ],
  "Before you buy": [
    "A guide to buying on Gumroad",
    "How do I give a product as a gift?",
    "Why did my payment fail?",
    "Safe buying on Gumroad",
    "Wishlists",
  ],
  "Accessing your purchase": [
    "How do I access my purchase?",
    "Your Gumroad Library",
    "Guide to memberships",
    "How to open ZIP and RAR files",
    "How do I send my purchases to Kindle?",
    "How do I send my purchase to Dropbox?",
    "When will my purchase be shipped?",
    "Rate and review your purchase",
  ],
  "Receipts and refunds": [
    "Get to know your Gumroad receipt",
    "How do I get a refund?",
    "I need an invoice",
    "I need a VAT refund",
    "I never received a receipt",
  ],
  "Issues with your purchase": [
    "There's an issue with my purchase",
    "Why was I charged by Gumroad?",
    "How do I cancel my membership?",
    "My purchase isn't downloading",
    "I'm not receiving updates",
    "Combining multiple accounts",
    "Why do I have a $1 charge from Gumroad?",
    "I have extra charges from Gumroad after my purchase",
    "How do I delete my credit card information?",
    "Incorrect recurring charge",
    "Report a Gumroad creator",
    "How do I contact Gumroad?",
  ],
};
