export const categoryGroups = {
  "Open an account": [
    { title: "Why choose Gumroad?", url: "/article/64-is-gumroad-for-me" },
    { title: "Account settings", url: "/64-is-gumroad-for-me" },
    { title: "Filling out payout settings", url: "" },
    { title: "Build a website on Gumroad", url: "" },
    { title: "Having multiple accounts", url: "" },
    { title: "Protecting creator privacy", url: "" },
    { title: "Account login security", url: "" },
    { title: "Things not allowed on Gumroad", url: "" },
    { title: "Selling services", url: "" },
    { title: "Adult content on Gumroad", url: "" },
    { title: "Deleting a Gumroad account", url: "" },
  ],
  "Add a product": [
    { title: "The products dashboard", url: "" },
    { title: "Adding a product", url: "" },
    { title: "Adding cover and thumbnail images", url: "" },
    { title: "Checkout customization", url: "" },
    { title: "Custom product URLs", url: "" },
    { title: "Unpublish or delete a product", url: "" },
    { title: "Setting up versions on a digital product", url: "" },
    { title: "Selling memberships", url: "" },
    { title: "Allowing installment plans", url: "" },
    { title: '"Pay what you want" pricing', url: "" },
    { title: "Prepare videos for streaming", url: "" },
    { title: "Compress videos using Handbrake", url: "" },
    { title: "Mobile-friendly files", url: "" },
    { title: "Metadata for audio files", url: "" },
    { title: "Becoming an affiliate on Gumroad", url: "" },
    { title: "File size limits", url: "" },
    { title: "Product bundles", url: "" },
    { title: "Collaborate with another creator", url: "" },
    { title: "Gumroad communities", url: "" },
  ],
  "Start selling": [
    { title: "Testing a purchase", url: "" },
    { title: "Gumroad Discover", url: "" },
    { title: "Find a product's URL", url: "" },
    { title: "The sales dashboard", url: "" },
    { title: "The sales analytics dashboard", url: "" },
    { title: "How Gumroad works for customers", url: "" },
    { title: "The Gumroad Library", url: "" },
    { title: "Gumroad mobile app", url: "" },
    { title: "Why customer payments fail", url: "" },
    { title: "Customers not receiving receipts", url: "" },
    { title: "Cancel customer memberships", url: "" },
    { title: "Issuing a refund", url: "" },
    { title: "Chargebacks on Gumroad", url: "" },
    { title: "Content protection on Gumroad", url: "" },
    { title: "Purchasing Power Parity", url: "" },
    { title: "Creating an Upsell", url: "" },
    { title: "Tipping", url: "" },
    { title: "More like this", url: "" },
    { title: "Set a custom refund policy", url: "" },
    { title: "Product bundles", url: "" },
  ],
  "Market your work": [
    { title: "Starting an email newsletter", url: "" },
    { title: "Send email updates", url: "" },
    { title: "Send automated emails with Workflows", url: "" },
    { title: "Customers not receiving emails", url: "" },
    { title: "Integrating Gumroad into websites", url: "" },
    { title: "Affiliates on Gumroad", url: "" },
    { title: "Product bundles", url: "" },
  ],
  "Get paid": [
    { title: "Getting paid by Gumroad", url: "" },
    { title: "Connect your Stripe account to Gumroad", url: "" },
    { title: "Adding PayPal to checkout", url: "" },
    { title: "Gumroad's fees", url: "" },
    { title: "The payouts dashboard", url: "" },
    { title: "Payoneer, Transferwise, and Gumroad", url: "" },
    { title: "What currency does Gumroad use?", url: "" },
    { title: "Payout delays", url: "" },
    { title: "Sales tax on Gumroad", url: "" },
    { title: "US sales tax on Gumroad", url: "" },
    { title: "EU & UK VAT on Gumroad", url: "" },
    { title: "Australian GST on Gumroad", url: "" },
    { title: "Indirect taxes on sales via Gumroad Discover", url: "" },
    { title: "Does Gumroad issue form 1099-K and 1099-MISC?", url: "" },
    { title: "Account suspension FAQ", url: "" },
    { title: "Fraudulent purchases", url: "" },
    { title: "Defining fraud on Gumroad", url: "" },
    { title: "Singaporean GST on Gumroad", url: "" },
  ],
  Advanced: [
    { title: "Discount codes", url: "" },
    { title: "Teams and Roles", url: "" },
    { title: "PDF stamping", url: "" },
    { title: "Facebook domain verification", url: "" },
    { title: "Product ratings and reviews", url: "" },
    { title: "Send customers to the payment form", url: "" },
    { title: "URL parameters", url: "" },
    { title: "Setting up a custom domain", url: "" },
    { title: "Third-party analytics", url: "" },
    { title: "Turn off third-party trackers", url: "" },
    { title: "Integrating products with external services", url: "" },
    { title: "Zapier integrations with Gumroad", url: "" },
    { title: "Create an application for the API", url: "" },
    { title: "License keys", url: "" },
    { title: "Accessibility statement for Gumroad", url: "" },
    { title: "Customer Moderation", url: "" },
  ],
  "Contact Gumroad": [
    { title: "Contact Gumroad", url: "" },
    { title: "Gumroad's refund policy", url: "" },
    { title: "Report a Gumroad creator", url: "" },
    { title: "DMCA counter notices", url: "" },
    { title: "Gumroad's subprocessors", url: "" },
    { title: "Supported browsers", url: "" },
    { title: "Jobs at Gumroad", url: "" },
  ],
  "Before you buy": [
    { title: "A guide to buying on Gumroad", url: "" },
    { title: "How do I give a product as a gift?", url: "" },
    { title: "Why did my payment fail?", url: "" },
    { title: "Safe buying on Gumroad", url: "" },
    { title: "Wishlists", url: "" },
  ],
  "Accessing your purchase": [
    { title: "How do I access my purchase?", url: "" },
    { title: "Your Gumroad Library", url: "" },
    { title: "Guide to memberships", url: "" },
    { title: "How to open ZIP and RAR files", url: "" },
    { title: "How do I send my purchases to Kindle?", url: "" },
    { title: "How do I send my purchase to Dropbox?", url: "" },
    { title: "When will my purchase be shipped?", url: "" },
    { title: "Rate and review your purchase", url: "" },
  ],
  "Receipts and refunds": [
    { title: "Get to know your Gumroad receipt", url: "" },
    { title: "How do I get a refund?", url: "" },
    { title: "I need an invoice", url: "" },
    { title: "I need a VAT refund", url: "" },
    { title: "I never received a receipt", url: "" },
  ],
  "Issues with your purchase": [
    { title: "There's an issue with my purchase", url: "" },
    { title: "Why was I charged by Gumroad?", url: "" },
    { title: "How do I cancel my membership?", url: "" },
    { title: "My purchase isn't downloading", url: "" },
    { title: "I'm not receiving updates", url: "" },
    { title: "Combining multiple accounts", url: "" },
    { title: "Why do I have a $1 charge from Gumroad?", url: "" },
    { title: "I have extra charges from Gumroad after my purchase", url: "" },
    { title: "How do I delete my credit card information?", url: "" },
    { title: "Incorrect recurring charge", url: "" },
    { title: "Report a Gumroad creator", url: "" },
    { title: "How do I contact Gumroad?", url: "" },
  ],
};
